In [1]:
from model import Model
from utils import fetch_dataset
from grakel.kernels import ShortestPath, VertexHistogram, EdgeHistogram

In [6]:
EH = Model(VertexHistogram, "MUTAG")

[[14  1  2 ...  0  0  0]
 [ 9  2  2 ...  0  0  0]
 [ 9  2  2 ...  0  0  0]
 ...
 [ 8  2  2 ...  0  0  0]
 [18  1  2 ...  0  0  0]
 [12  2  2 ...  0  0  0]]
Accuracy for MUTAG is 0.8157894736842105


In [3]:
MUTAG = fetch_dataset("MUTAG", verbose=False)
EH = VertexHistogram(normalize=False)

In [4]:
feature = EH.fit(MUTAG.data).X
feature

<188x7 sparse matrix of type '<class 'numpy.int64'>'
	with 586 stored elements in Compressed Sparse Row format>

In [5]:
import scipy
type(feature.X) == scipy.sparse.csr.csr_matrix

AttributeError: X not found